version: '3'
services:
  node:
    build:
      dockerfile: ./dockerfile
      context: .
    image: nodeapp
    container_name: app_node
    ports:
      - 3000:3000
    volumes:
      - /c/Users/luis.santana/Estudos/bootcamp/gobarber:/usr/app
